plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'com.project.scheduleasy'
    compileSdk 35

    defaultConfig {
        applicationId "com.project.scheduleasy"
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

dependencies {

    implementation libs.appcompat
    implementation libs.material
    implementation libs.activity
    implementation libs.constraintlayout
    implementation libs.material.v1110
    implementation libs.recyclerview
    implementation libs.gson
    implementation libs.zoomlayout
    implementation libs.core  // or latest version
    implementation libs.itext7.core // PDF generation
    implementation libs.core.ktx
    implementation libs.preference// For file operations
    implementation libs.room.runtime
    annotationProcessor libs.room.compiler
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core
}